version: '3.8'

services:
  mysql:
    image: mysql/mysql-server:8.0
    ports:
      - '3306:3306'
    container_name: '${APP_NAME:-dev}-mysql'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASS}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASS}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'dev-mysql:/var/lib/mysql'
      - './db/schema.sql:/docker-entrypoint-initdb.d/0.sql'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASS}"]
      timeout: 10s
      retries: 10
    networks:
      - internalnet

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    container_name: '${APP_NAME:-dev}-pma'
    environment:
      PMA_ARBITRARY: 1
      PMA_PORT: 3306
      PMA_HOST: mysql
      PMA_USER: '${DB_USER}'
      PMA_PASSWORD: '${DB_PASS}'
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge

volumes:
  dev-mysql:
    driver: local
